# Generated by Django 3.2.7 on 2023-01-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='滞在終了時間'),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='滞在開始時間'),
        ),
    ]
