# Generated by Django 3.2.7 on 2023-01-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplan', '0002_auto_20230117_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'Plan'},
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日時'),
        ),
    ]
