# Generated by Django 3.2.7 on 2023-01-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplan', '0002_auto_20230117_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('prefecture_code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='都道府県コード')),
                ('prefecture_name', models.CharField(max_length=4, verbose_name='都道府県名')),
            ],
            options={
                'verbose_name_plural': 'Prefecture',
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'Plan'},
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日時'),
        ),
    ]
